image: .gitpod.Dockerfile

tasks:
    - name: setup
      init: |
       java -version
       docker run -d --name redis-server -p 6379:6379 redis

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java