image: 
    file: .gitpod.Dockerfile

tasks:
    - name: setup
      init: |
        docker run -d \
        --name mongo \
        -p 27017:27017 \
        -e MONGO_INITDB_ROOT_USERNAME=admin \
        -e MONGO_INITDB_ROOT_PASSWORD=admin \
        mongo
    
        docker run -d --name redis-server -p 6379:6379 redis

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
