spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cloudburst?authSource=admin

  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
server:
  port: 8080

logging:
  file:
    name: logs/cloudbuster.log
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans
