spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@mongo:27017/cloudburst?authSource=admin

  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}

  session:
    store-type: redis

server:
  port: 8080

logging:
  file:
    name: logs/cloudburst.log
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans
